### ISSUE TITLE
Support TopicId as input

### ISSUE THREAD

**Issue by cachius** [AngryLoki/mreid-resolver#8]
Hey there,

It would be useful to so support TopicIds as Input,
basically a reverse of [buildTopicId](https://github.com/AngryLoki/mreid-resolver/blob/eaecc44bab6cc0e6f922c1c39bf1c265e3d0622e/src/routes/google-news.ts#L28).

Kind regards!

**Comment by AngryLoki** [comment]
Hi @cachius , check this out - now you can enter topic ids as described in https://angryloki.github.io/mreid-resolver/ :)
